server:
  port: 8085

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/orianna
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: validate
  flyway:
    locations: classpath:/database/migration

application:
  swagger:
    title: Orianna API
    description: Boilerplate API documentation
    version: 1.0.0
    terms-of-service-url:
    contact-name: Nemanja Mudrinic
    contact-url: nucleus-it.com
    contact-email: mudrinic.nemanja@itengine.co.rs
    license:
    license-url:
  security:
    secret: suelcun
    expiration: 18000
