server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orianna
    username: root
    password: root

application:
  swagger:
    title: Orianna API
    description: API documentation for driving school application
    version: 1.0.0
    terms-of-service-url:
    contact-name: Nemanja Mudrinic
    contact-url: nucleus-it.com
    contact-email: mudrinic.nemanja@itengine.co.rs
    license:
    license-url:
